# Controls when the workflow will run
on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [default]

name: Deploy website on push
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v4

      - name: Install node dependencies
        run: |
          npm install

      - name: Build with Astro
        run: |
          npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            dist/

      - name: Upload
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ vars.FTP_SERVER }}
          username: ${{ vars.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ vars.FTP_PATH }}
          local-dir: dist/
